//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPr18Generalskiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceOfDiscipline
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Номер_зачётной_книжки { get; set; }
        public string Общежитие { get; set; }
        public Nullable<int> Индекс_группы { get; set; }
        public Nullable<int> География { get; set; }
        public Nullable<int> Математика { get; set; }
        public Nullable<int> Биология { get; set; }
        public Nullable<int> Физика { get; set; }
        public Nullable<int> Химия { get; set; }
    }
}
